apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmrollout.fullname" . }}
  labels:
    {{- include "helmrollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmrollout.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmrollout.fullname" . }}-preview
  labels:
    {{- include "helmrollout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helmrollout.selectorLabels" . | nindent 4 }}

